make a cleaner travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,71 +1,80 @@
 # Travis CI Configuration File
-sudo: false
-dist: trusty
 language: php
+
+services:
+  - mysql
+
 cache:
-  apt: true
   directories:
     - $HOME/.composer/cache
     - node_modules
-    - vendor
-env:
-  global:
-    - WP_VERSION=latest WP_MULTISITE=0
 
-# Test main supported versions of PHP against latest WP.
+# Explicitly test against supported versions of PHP
+#
+# Reference: https://www.php.net/supported-versions.php
 php:
-  - 5.6
-  - 7.0
-  - 7.1
-  - 7.2
+  - 7.4
   - 7.3
 
-notifications:
-  email:
-    on_success: never
-    on_failure: change
+# Test against the latest version of WordPress and one version back.
+env:
+  - WP_VERSION=latest
+  - WP_VERSION=5.4
 
-branches:
-  only:
-    - master
-
-# PHP/WP versions
+# Customize the build matrix.
 matrix:
   fast_finish: true
   include:
-  - name: "Coding standard check"
-    php: 7.2
-    env: WP_VERSION=latest WP_MULTISITE=0 RUN_PHPCS=1
-  - name: "Unit tests code coverage"
-    php: 7.3
-    env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1
-  - name: "Object Sync for Salesforce unit tests using WordPress nightly"
-    php: 7.3
-    env: WP_VERSION=nightly WP_MULTISITE=0
-  - php: 7.4snapshot
-    env: WP_VERSION=nightly WP_MULTISITE=0
-  allow_failures:
-  - php: 7.3
-    env: WP_VERSION=latest WP_MULTISITE=0 RUN_CODE_COVERAGE=1
-  - php: 7.4snapshot
-    env: WP_VERSION=nightly WP_MULTISITE=0
+    # Run PHP_CodeSniffer
+    - name: Coding standards
+      php: 7.4
+      env: WP_VERSION=latest WP_TRAVISCI=phpcs
 
-before_script:
+    # Canary for our oldest-supported version
+    - name: Legacy
+      php: 5.6
+      env: WP_VERSION=4.9
+
+    # Nightly versions of PHP and WordPress.
+    - name: Bleeding edge
+      php: 8.0
+      env: WP_VERSION=trunk
+
+  # Jobs that are permitted to fail without breaking the build
+  allow_failures:
+    - name: Bleeding edge
+
+before_install:
   - export PATH="$HOME/.composer/vendor/bin:$PATH"
-  - export WP_TESTS_DIR=/tmp/wordpress/tests/phpunit
-  - export WP_CORE_DIR=/tmp/wordpress/
+
+  # Unless we need XDebug, disable it for improved performance.
+  - phpenv config-rm xdebug.ini || return 0
+
+install:
+  # Install our Composer dependencies
+  - composer install --prefer-dist --no-interaction
+
+  # Install an older version of PHPUnit if we're still running PHP 5.6.
   - |
-    # Remove Xdebug for a huge performance increase:
-    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
-      phpenv config-rm xdebug.ini
+    if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then
+      wget -O ./vendor/bin/phpunit https://phar.phpunit.de/phpunit-5.phar
+      chmod +x ./vendor/bin/phpunit
+    fi
+
+  # Install the WordPress core test suite
+  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
+
+script:
+  - |
+    # If we've set the $WP_TRAVISCI variable to run PHPCS, do that instead
+    # of running PHPUnit.
+    if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
+      ./vendor/bin/phpcs
+
     else
-      echo "xdebug.ini does not exist"
+      # Execute the test suite
+      ./vendor/bin/phpunit
+
+      # Optionally run the tests again in a multisite environment
+      #WP_MULTISITE=1 ./vendor/bin/phpunit
     fi
-  - composer install --no-dev
-  - |
-    # Install WP Test suite, install PHPUnit globally:
-    if [[ ! -z "$WP_VERSION" ]]; then
-      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
-      composer global require "phpunit/phpunit=5.7.*|7.5.*"
-    fi
-  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
